# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-1
#   namespace: app-1
#   labels:
#     app: app-1
# spec:
#   replicas: 10
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#   selector:
#     matchLabels:
#       app: app-1
#   template:
#     metadata:
#       labels:
#         app: app-1
#     spec:
#       containers:
#       - name: app-1
#         image: mauriciopgomes/app-1
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
#           protocol: TCP
#         livenessProbe:
#           httpGet:
#             path: /
#             port: 80
#           initialDelaySeconds: 5
#           periodSeconds: 5
#         startupProbe:
#           httpGet:
#             path: /
#             port: 80
#         resources:
#           requests:
#             cpu: "250m"
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
