apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  namespace: app
  labels:
    app: app-1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: mauriciopgomes/app-1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: app
spec:
  selector:
    app: app-1
  ports:
    - name: http
      protocol: TCP
      port: 80
  type: NodePort
