apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml
namespace: app
images:
- name: app-1
  newName: mauriciopgomes/app-1
  newTag: 679a0600f78f9bf264a269d720237c3553cbf669
