apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: app
images:
- name: app-1
  newName: mauriciopgomes/app-1
  newTag: 107b40f1bb7c3c547c4cbe1b58b90f5ee4aeaab9
