app1:
  app1:
    image:
      repository: mauriciopgomes/app-1
      tag: latest
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 250m
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 0
  replicas: 10
  type: loadbalancer
kubernetesClusterDomain: cluster.local
